// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhCyvajg_f_jUM03XDpY5VY6e9ctMhFVQ',
    appId: '1:397874331557:android:ecc2898482d2202d79724c',
    messagingSenderId: '397874331557',
    projectId: 'shop-map-5c223',
    storageBucket: 'shop-map-5c223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqc1wnA79FGlrYp_l-Hij5b7CrMUL6Tk',
    appId: '1:397874331557:ios:3c82fd876ffd220f79724c',
    messagingSenderId: '397874331557',
    projectId: 'shop-map-5c223',
    storageBucket: 'shop-map-5c223.appspot.com',
    androidClientId: '397874331557-7814sas44oau641lfm4ldpefn7gc8g1s.apps.googleusercontent.com',
    iosClientId: '397874331557-380v1rh94o02c4fmapvu8e3f9th7i55e.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopMap',
  );
}
